### ISSUE TITLE
Memory exhaustion when chaining oauth

### ISSUE THREAD

**Issue by ypl-github** [rztuc/dokuwiki-plugin-authchained#14]
Good day!

When trying to log in using authchained I get an empty page and the following error message in the log:

[Fri Aug 21 11:24:42.293817 2020] [:error] [pid 25112] [client xxx:60840] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 262144 bytes) in /usr/share/dokuwiki/inc/auth.php on line 225, referer: https://xxx/doku.php?id=start&do=login&sectok=

The message does not change significantly if I allow less memory.

I have the following:
$conf['authtype'] = 'authchained';
$conf['plugin']['authchained']['authtypes'] = 'oauth:authplain';
$conf['plugin']['authchained']['usermanager_authtype'] = 'authplain';
$conf['auth_security_timeout'] = 24*60*60;
$conf['plugin']['oauth']['xxx-key'] = 'xxx';
$conf['plugin']['oauth']['xxx-secret'] = 'xxx';
$conf['plugin']['oauth']['xxx-authurl']  = 'https://xxx/oauth/authorize';
$conf['plugin']['oauth']['xxx-tokenurl'] = 'https://xxx/oauth/token';
$conf['plugin']['oauth']['singleService'] = 'xxx';
$conf['plugin']['oauth']['register-on-auth'] = 1;

The configuration works, when I use
$conf['authtype'] = 'oauth';
or
$conf['authtype'] = 'authplain';

Did I misunderstand anything?

cu

AW

**Comment by einhirn** [comment]
As far as I see it, you don't even need Authchained for "Authplain" and "Oauth". From https://www.dokuwiki.org/plugin:oauth :
> This plugin sits on top of the usual authplain authentication mechanism. Password based logins will continue to work and users can still register directly at your wiki, unless you configure it otherwise. 

I guess memory exhaustion occurs because oauth also loads a secondary auth plugin itself, there's probably some kind of endless recursion involved. So, while I don't have the ressources to look into it any further, I think that, in this use case, you don't need authchained anyway.
